### ISSUE TITLE
Tension Pool display

### ISSUE THREAD

**Issue by corerupt83** [SDoehren/tension-pool#26]
**Describe the bug**
The tension Pool display count, below the chat log, does not render properly after you right click the chat log icon at the top right menu. It renders fine normally, but bugs out when you want the chat in it's own window.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the menu, top right in foundry.
2. Right click on the chat log
3. See the tension pool display kind of squashing the chat window that opens, and not displaying correctly.

**Expected behaviour**
To display as though still attached to the main menu window on the right. 

**Screenshots**
![example of chat window](https://user-images.githubusercontent.com/36152926/143723679-4c18cefb-8d8e-43b5-a744-61be5a29d5eb.jpg)

**Foundry (please complete the following information):**
 - Foundry Version 0.8.9
 - System [PF2E]
 - Module Version [e.g. 0.0.55]

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [N/A Using program]
 - Version [N/A]

**Additional context**

**Comment by SDoehren** [comment]
that's a very weird bug.  

is this a random find or are you right clicking for a reason?

**Comment by corerupt83** [comment]
Right clicking because I stretch foundry over two monitors and would like to have the chat open on my left monitor to see the rolls better, as I play with the map on that monitor and have other information open on the other monitor. 

The only reason I came across this issue. If you could fix that it would be great. Tried looking at your code myself but it boggles my mind lol

**Comment by Mattrogers13** [comment]
I have encountered a similar if not the same issue. 

Describe the bug
The tension Pool display count, below the chat log, does not render properly after you right click the chat log icon at the top right menu. It renders fine normally, but bugs out when you want the chat in it's own window.

To Reproduce
Steps to reproduce the behaviour:

Go to the menu, top right in foundry.
Right click on the chat log
See the tension pool display kind of squashing the chat window that opens, and not displaying correctly.
Expected behaviour
To display as though still attached to the main menu window on the right.

Screenshots
If applicable, add screenshots to help explain your problem.
example of chat window
![Screen Shot 2021-12-15 at 9 04 32 PM](https://user-images.githubusercontent.com/48500042/146294673-b5c6abc6-f8c5-45c0-930d-73ce7f0e922e.png)

Foundry (please complete the following information):

Foundry Version 0.8.9
System 5e 1.5.5

Desktop (please complete the following information):
OS: [Mac OS 10.15.7]
Browser [N/A Using program]
Additional information: all modules are disabled with the exception of Tension Pool, Dice so Nice, and Library: Chat Commands.

**Comment by SDoehren** [comment]
I have found, at a minimum, a temporary fix that at least stops it being massive.

This will be released as part of the v9 update.

**Comment by SDoehren** [comment]
I believe I have a solution for a fully working pool in the popup; currently in testing.

**Comment by SDoehren** [comment]
Resolved in latest release
